const cfg=window.FV_CONFIG||{};
const VEGS=[
{name:'Tomato',cat:'Fresh',price:40,unit:'kg',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Tomato.png',farmer:'Patil Fresh Fields',desc:'Juicy, ripe tomatoes for daily cooking.',badge:'Harvested Today'},
{name:'Potato',cat:'Root',price:35,unit:'kg',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Potato.png',farmer:'Jadhav Root Farm',desc:'Everyday potatoes, sorted fresh.',badge:'Farm Fresh'},
{name:'Carrot',cat:'Root',price:60,unit:'kg',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Karotte.png',farmer:'Jadhav Root Farm',desc:'Crisp carrots with natural sweetness.',badge:'Fresh Pick'},
{name:'Onion',cat:'Root',price:45,unit:'kg',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Onion.png',farmer:'Jadhav Root Farm',desc:'Kitchen staple sourced from local growers.',badge:'Daily Essential'},
{name:'Green Chilli',cat:'Fresh',price:80,unit:'kg',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Chili.png',farmer:'Patil Fresh Fields',desc:'Fresh green chillies with a bright bite.',badge:'Fresh'},
{name:'Spinach',cat:'Leafy',price:30,unit:'bunch',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Spinach.png',farmer:'Deshmukh Green Farm',desc:'Tender leafy greens packed close to delivery.',badge:"Today's Harvest"},
{name:'Cabbage',cat:'Leafy',price:35,unit:'kg',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Cabbage.png',farmer:'Deshmukh Green Farm',desc:'Crisp cabbage for sabzi and salads.',badge:'Farm Fresh'},
{name:'Cauliflower',cat:'Special',price:55,unit:'kg',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Cauliflower.png',farmer:'Deshmukh Green Farm',desc:'Seasonal cauliflower, carefully sorted.',badge:'Seasonal'},
{name:'Broccoli',cat:'Special',price:120,unit:'kg',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Broccoli.png',farmer:'Deshmukh Green Farm',desc:'Fresh broccoli for healthy meals.',badge:'Premium'},
{name:'Capsicum',cat:'Fresh',price:90,unit:'kg',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Capsicum.png',farmer:'Patil Fresh Fields',desc:'Crisp green capsicum with a fresh crunch.',badge:'Fresh'},
{name:'Beetroot',cat:'Root',price:65,unit:'kg',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Beetroot.png',farmer:'Jadhav Root Farm',desc:'Vibrant beetroot, great for sabzi and juice.',badge:'Farm Pick'},
{name:'Coriander',cat:'Herbs',price:20,unit:'bunch',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Coriander.png',farmer:'Deshmukh Green Farm',desc:'Fragrant coriander harvested for freshness.',badge:'Morning Harvest'},
{name:'Lady Finger',cat:'Fresh',price:70,unit:'kg',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Okra.png',farmer:'Patil Fresh Fields',desc:'Tender okra selected for daily kitchens.',badge:'Fresh'},
{name:'Brinjal',cat:'Fresh',price:55,unit:'kg',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Aubergine.png',farmer:'Patil Fresh Fields',desc:'Fresh local brinjal for everyday recipes.',badge:'Local Farm'},
{name:'Bottle Gourd',cat:'Fresh',price:40,unit:'kg',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Bottle_gourd.png',farmer:'Patil Fresh Fields',desc:'Light, fresh bottle gourd.',badge:'Daily Fresh'},
{name:'Green Peas',cat:'Special',price:110,unit:'kg',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Peas_in_pod.png',farmer:'Deshmukh Green Farm',desc:'Sweet green peas when in season.',badge:'Seasonal'}
];
const FARMERS=[
{name:'Ramesh Patil',farm:'Patil Fresh Fields',loc:'Buldhana, Maharashtra',specialty:'Tomato · chilli · seasonal vegetables',story:'Family farming with a focus on fresh, short-distance supply.'},
{name:'Sunita Deshmukh',farm:'Deshmukh Green Farm',loc:'Buldhana, Maharashtra',specialty:'Leafy greens · herbs · seasonal greens',story:'Harvests leafy produce close to dispatch so it reaches kitchens crisp.'},
{name:'Mahesh Jadhav',farm:'Jadhav Root Farm',loc:'Buldhana, Maharashtra',specialty:'Potato · carrot · onion · beetroot',story:'Local root-vegetable grower supplying nearby households.'}
];
let cart=JSON.parse(localStorage.getItem('fv_cart')||'[]');let category='All';let orders=JSON.parse(localStorage.getItem('fv_orders')||'[]');
const $=s=>document.querySelector(s),money=n=>'₹'+Number(n).toLocaleString('en-IN',{maximumFractionDigits:2});
function save(){localStorage.setItem('fv_cart',JSON.stringify(cart));localStorage.setItem('fv_orders',JSON.stringify(orders));}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2600)}
function toggleMenu(){$('#nav').classList.toggle('show')}
function cats(){const list=['All','Leafy','Root','Fresh','Special','Herbs'];$('#chips').innerHTML=list.map(x=>`<button class="chip ${category===x?'active':''}" onclick="category='${x}';cats();renderProducts()">${x==='All'?'🥬':x==='Leafy'?'🌿':x==='Root'?'🥕':x==='Fresh'?'🍅':x==='Special'?'🥦':'🌱'} ${x}</button>`).join('')}
function renderProducts(){cats();let q=($('#search')?.value||'').toLowerCase();let list=VEGS.filter(v=>(category==='All'||v.cat===category)&&(!q||`${v.name} ${v.desc} ${v.farmer}`.toLowerCase().includes(q)));let sort=$('#sort')?.value;if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));$('#products').innerHTML=list.map(v=>{let i=cart.find(x=>x.name===v.name);return `<article class="product"><span class="badge">${v.badge}</span><div class="product-img"><img src="${v.img}" alt="${v.name}" loading="lazy" onerror="this.style.display='none'"/></div><h3>${v.name}</h3><div class="farmer">🚜 ${v.farmer}</div><div class="product-bottom"><div class="price">${money(v.price)} <small>/ ${v.unit}</small></div>${i?`<div class="qty"><button onclick="changeQty('${v.name}',-1)">−</button><b>${i.qty}</b><button onclick="changeQty('${v.name}',1)">+</button></div>`:`<button class="add" onclick="addToCart('${v.name}')">Add +</button>`}</div></article>`}).join('')||'<div class="notice">No vegetables found. Try another search.</div>'}
function addToCart(name){let i=cart.find(x=>x.name===name);if(i)i.qty++;else{let v=VEGS.find(x=>x.name===name);cart.push({name:v.name,qty:1,price:v.price,unit:v.unit,img:v.img})}save();renderProducts();renderCart();toast(`${name} added to basket`)}
function changeQty(name,d){let i=cart.find(x=>x.name===name);if(!i)return;i.qty+=d;if(i.qty<=0)cart=cart.filter(x=>x.name!==name);save();renderProducts();renderCart()}
function totals(){let sub=cart.reduce((s,x)=>s+x.price*x.qty,0),fee=sub>=cfg.freeDeliveryMin?0:(sub?cfg.deliveryFee:0);return{sub,fee,total:sub+fee}}
function renderCart(){let t=totals();$('#cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0);$('#cartItems').innerHTML=cart.length?cart.map(x=>`<div class="cart-line"><img src="${x.img}" alt="${x.name}"><div><b>${x.name}</b><small>${money(x.price)} / ${x.unit}</small></div><div class="qty"><button onclick="changeQty('${x.name}',-1)">−</button><b>${x.qty}</b><button onclick="changeQty('${x.name}',1)">+</button></div></div>`).join(''):'<div class="notice">Your basket is empty. Add some fresh vegetables 🌱</div>';$('#subtotal').textContent=money(t.sub);$('#delivery').textContent=t.fee?money(t.fee):'FREE';$('#total').textContent=money(t.total);let n=$('#paymentRule');if(t.sub>=500){n.classList.remove('hidden');n.textContent='🔒 Orders of ₹500+ require online payment before delivery.'}else{n.classList.add('hidden')}}
function openCart(){$('#cart').classList.add('open');$('#overlay').classList.add('show')}function closeCart(){$('#cart').classList.remove('open');$('#overlay').classList.remove('show')}
function openCheckout(){if(!cart.length)return toast('Add vegetables before checkout');closeCart();$('#checkout').classList.add('open');updatePaymentRule();}
function closeCheckout(){$('#checkout').classList.remove('open')}
function updatePaymentRule(){let t=totals();let cod=$('#codOption'),codRadio=cod.querySelector('input');if(t.sub>=500){cod.style.opacity='.45';codRadio.disabled=true;codRadio.checked=false;document.querySelector('input[value="online"]').checked=true;$('#checkoutNotice').textContent='🔒 ₹500+ orders must be paid online before delivery.'}else{cod.style.opacity='1';codRadio.disabled=false;$('#checkoutNotice').textContent='💳 Online payment or cash on delivery below ₹500.'}$('#checkoutTotal').textContent=money(t.total);document.querySelectorAll('.pay').forEach(x=>x.classList.toggle('selected',x.querySelector('input').checked))}
function currentPayment(){return document.querySelector('input[name="payment"]:checked')?.value||'online'}
async function placeOrder(e){e.preventDefault();let t=totals(),payment=currentPayment(),name=$('#cName').value.trim(),phone=$('#cPhone').value.trim(),email=$('#cEmail').value.trim(),address=$('#cAddress').value.trim(),pin=$('#cPin').value.trim();if(!/^[6-9]\d{9}$/.test(phone))return toast('Enter a valid 10-digit mobile number');if(!/^\d{6}$/.test(pin))return toast('Enter a valid 6-digit pincode');if(t.sub>=500&&payment==='cod')return toast('₹500+ orders require online payment');let order={id:'FV-'+Date.now().toString(36).toUpperCase(),createdAt:new Date().toISOString(),customer:{name,phone,email,address,city:'Buldhana',pincode:pin},slot:$('#cSlot').value,items:cart.map(x=>({...x})),subtotal:t.sub,delivery:t.fee,total:t.total,paymentMethod:payment,paymentStatus:payment==='cod'?'pending':'paid',status:payment==='cod'?'placed':'placed',statusHistory:[{status:'placed',at:new Date().toISOString()}]};if(payment==='online'&&cfg.razorpayKeyId&&window.Razorpay){try{await razorpayTest(order)}catch(err){return toast(err.message||'Payment cancelled')}}else if(payment==='online'){const ok=confirm(`TEST PAYMENT\n\nOrder ${order.id}\nAmount ${money(order.total)}\n\nClick OK to simulate successful test payment.`);if(!ok)return toast('Payment cancelled')}orders.unshift(order);save();sendEmail(order);openWhatsApp(order);cart=[];save();renderProducts();renderCart();showSuccess(order)}
function razorpayTest(order){return new Promise((resolve,reject)=>{let r=new Razorpay({key:cfg.razorpayKeyId,amount:Math.round(order.total*100),currency:'INR',name:'FreshVeggies',description:`Test order ${order.id}`,prefill:{name:order.customer.name,email:order.customer.email,contact:order.customer.phone},theme:{color:'#164b2b'},handler:res=>{order.paymentStatus='paid';order.razorpayPaymentId=res.razorpay_payment_id;resolve()},modal:{ondismiss:()=>reject(new Error('Payment cancelled'))}});r.open()})}
function showSuccess(o){$('#success').classList.remove('hidden');$('#checkoutForm').classList.add('hidden');$('#success').innerHTML=`<div style="font-size:52px">🌱</div><h3>Order received!</h3><p><b>${o.id}</b><br>${money(o.total)} · ${o.paymentMethod==='cod'?'Cash on delivery':'Online paid'}<br>Delivery: ${o.slot}<br><b>Buldhana</b></p><div class="notice">Manager will move your order through Confirmed → Preparing → Dispatched → Out for delivery → Delivered. You can see updates in My Orders.</div><div style="display:flex;gap:8px;justify-content:center;flex-wrap:wrap"><button class="btn primary" onclick="openProfile();closeCheckout()">View order</button><a class="btn secondary" target="_blank" href="${waUrl(o)}">WhatsApp manager</a></div>`}
function waUrl(o){let lines=[`FreshVeggies order ${o.id}`,`Customer: ${o.customer.name}`,`Phone: ${o.customer.phone}`,`Address: ${o.customer.address}, Buldhana - ${o.customer.pincode}`,`Slot: ${o.slot}`,`Payment: ${o.paymentMethod} / ${o.paymentStatus}`,`Total: ${money(o.total)}`,'Items:',...o.items.map(x=>`${x.name} × ${x.qty} = ${money(x.price*x.qty)}`)];return`https://wa.me/${String(cfg.adminWhatsApp||'').replace(/\D/g,'')}?text=${encodeURIComponent(lines.join('\n'))}`}
function openWhatsApp(o){if(!cfg.adminWhatsApp||cfg.adminWhatsApp.includes('X'))return;/* For GitHub Pages, WhatsApp must be opened by the customer; the link is available in confirmation. */}
async function sendEmail(o){let e=cfg.emailjs||{};if(!e.publicKey||!e.serviceId||!e.templateId||!window.emailjs)return;try{emailjs.init(e.publicKey);await emailjs.send(e.serviceId,e.templateId,{order_id:o.id,customer_name:o.customer.name,phone:o.customer.phone,email:o.customer.email,address:`${o.customer.address}, Buldhana - ${o.customer.pincode}`,slot:o.slot,items:o.items.map(x=>`${x.name} × ${x.qty}`).join(', '),total:money(o.total),payment_status:o.paymentStatus})}catch(err){console.warn('EmailJS notification failed',err)}}
function openProfile(){closeCart();$('#profile').classList.add('open');profileTab('orders',$('.profile-tabs button'))}function closeProfile(){$('#profile').classList.remove('open')}
function profileTab(tab,btn){document.querySelectorAll('.profile-tabs button').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');if(tab==='orders'){ $('#profileOrders').classList.remove('hidden');$('#profileDetails').classList.add('hidden');renderProfileOrders()}else{$('#profileOrders').classList.add('hidden');$('#profileDetails').classList.remove('hidden');renderProfileDetails()}}
function statusSteps(){return['placed','confirmed','preparing','dispatched','out_for_delivery','delivered']}
function prettyStatus(s){return({placed:'Placed',confirmed:'Confirmed',preparing:'Preparing',dispatched:'Dispatched',out_for_delivery:'Out for delivery',delivered:'Delivered',cancelled:'Cancelled'})[s]||s}
function renderProfileOrders(){if(!orders.length){$('#profileOrders').innerHTML='<div class="profile-detail"><div class="notice">No orders on this device yet. Your next basket will appear here.</div></div>';return}$('#profileOrders').innerHTML=orders.map(o=>{let idx=statusSteps().indexOf(o.status);return `<div class="order-profile"><div style="display:flex;justify-content:space-between;gap:10px"><div><h3>${o.id}</h3><small>${new Date(o.createdAt).toLocaleString('en-IN')}</small></div><b>${money(o.total)}</b></div><div class="order-status">${statusSteps().map((s,i)=>`<span class="status-pill ${i<=idx?'done':''}">${i<=idx?'✓ ':''}${prettyStatus(s)}</span>`).join('')}</div><small>${o.items.map(x=>`${x.name} × ${x.qty}`).join(' · ')}</small><div class="notice">📍 ${o.customer.address}, Buldhana · ${o.slot}<br>Payment: ${o.paymentMethod} · ${o.paymentStatus}</div></div>`}).join('')}
function renderProfileDetails(){let o=orders[0];let c=o?.customer;$('#profileDetails').innerHTML=`<div class="profile-detail"><p><b>Delivery location</b><br>Buldhana, Maharashtra, India</p><p><b>Saved details</b><br>${c?`${c.name}<br>${c.phone}<br>${c.email}<br>${c.address}<br>Buldhana - ${c.pincode}`:'Your details will appear here after your first order.'}</p><button class="btn primary" onclick="closeProfile();openCheckout()">Order again →</button></div>`}
function reveal(){document.querySelectorAll('.reveal').forEach(x=>new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.1}).observe(x))}
function renderFarmers(){$('#farmersGrid').innerHTML=FARMERS.map(f=>`<article class="farmer-card"><div class="farmer-avatar">👨‍🌾</div><h3>${f.name}</h3><b>${f.farm}</b><small>${f.loc}</small><p>${f.story}</p><small>🌱 ${f.specialty}</small></article>`).join('')}
document.querySelectorAll('input[name="payment"]').forEach(x=>x.addEventListener('change',updatePaymentRule));
renderProducts();renderFarmers();renderCart();reveal();
